[nfs]
172.31.29.150 ansible_ssh_user='ec2-user'

[webservers]
172.31.23.254 ansible_ssh_user='ec2-user'
172.31.16.9 ansible_ssh_user='ec2-user'

[db]
172.31.16.130 ansible_ssh_user='ec2-user'

[lb]
172.31.90.161 ansible_ssh_user='ubuntu'